### ISSUE TITLE
chains only load after restarting script

### ISSUE THREAD

**Issue by Insaneshane99** [doritohead/qb-chains#1]
Chains only appear on player after restarting qb-chains while on server

when I first login and try to put the chain on nothing appears, once i restart qb-chains and use item again chain appears

I do not get any server or client side errors

Im using game version b2372

**Comment by Insaneshane99** [comment]
Ive gone through the Stream folder and removed half the chain .ytd files to try and reduce how many models can load into the game as there appears to be an issue with that https://github.com/DurtyFree/durty-cloth-tool/wiki/YMT-game-limit-and-crash-issues 

However even after doing this the issue persists.

The weird thing is other clothing scripts work fine , i have https://github.com/elvodkaa/qb-bandana  installed and it works flawlessly.

I have also tried removing my other clothing scripts and it still dont work without restarting it.

**Comment by doritohead** [comment]
Thank you for contacting, i believe this is fixed now after altering the postioning of a local.
